#!/bin/bash

if [ -z "$1" ]; then
  echo "error: must specify host name" >&2
  exit 1
fi

set -x

git archive --prefix=cfdbox2/ --format=tar.gz HEAD | ssh $1 'tar -C $HOME -xvzf -'
ssh $1 'cd $HOME/cfdbox2 && python setup.py develop'
